### ISSUE TITLE
mock fails when told to return nil

### ISSUE THREAD

**Issue by goblimey** [petergtz/pegomock#24]
I have an interface called Template:

package template

import (
    "io"
)

type Template interface {
    // Execute executes the template
    Execute(wr io.Writer, data interface{}) error
}

The Execute method returns nil if there is no error.

I create a mock called mockTemplate and specify this:

pegomock.When(mockTemplate.Execute(writer, &form)).ThenReturn(nil)

I get this error:

panic: interface conversion: interface is nil, not error [recovered]
    panic: interface conversion: interface is nil, not error [recovered]
    panic: interface conversion: interface is nil, not error

goroutine 5 [running]:
panic(0x782820, 0xc420016b00)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc420096180)
    /usr/local/go/src/testing/testing.go:579 +0x25d
panic(0x782820, 0xc420016b00)
    /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/golang/mock/gomock.(_Controller).Finish(0xc4200d8aa0)
    /home/simon/gocode/src/github.com/golang/mock/gomock/controller.go:149 +0x320
panic(0x782820, 0xc420016b00)
    /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/goblimey/films/mocks/pe.(_MockTemplate).Execute(0xc420036040, 0x9811c0, 0xc420036038, 0x7a0aa0, 0xc420016900, 0x0, 0x0)
    /home/simon/eclipse.workspaces/films4/films/src/github.com/goblimey/films/mocks/pe/mock_template.go:27 +0x1e5

(and so on)

The problem is in the last line of the generated Execute method:

func (mock *MockTemplate) Execute(_param0 io.Writer, _param1 interface{}) error {
    result := pegomock.GetGenericMockFrom(mock).Invoke("Execute", _param0, _param1)
    if len(result) == 0 {
        var ret0 error
        return ret0
    }
    return result[0].(error)
}

The problem is that result[0] is nil.

I hacked the mock to make it check for nil:

func (mock *MockTemplate) Execute(_param0 io.Writer, _param1 interface{}) error {
    result := pegomock.GetGenericMockFrom(mock).Invoke("Execute", _param0, _param1)
    if len(result) == 0 {
        var ret0 error
        return ret0
    }
    if result[0] == nil {
        return nil
    } else {
        return result[0].(error)
    }
}

Now it works.

You may need to make a similar change in other places too.

**Comment by petergtz** [comment]
Hi @goblimey,

Thanks for reporting this!

I've just pushed a fix. Can you try again and see if that solves your issue?

**Comment by goblimey** [comment]
As far as I can see, that doesn't fix my problem.  

I ran 

$ go get -u github.com/petergtz/pegomock

 I checked the last written date of one of the file you changed - dsl_test.go, and had a look at it to check that it contained the change.

Just to make sure, I ran

$ go install github.com/petergtz/pegomock

and rebuilt my mocks (easily forgotten!).

I looked at the generated mock and it looks the same as before, and when I run my test, I get the same problem.  Also, today I discovered that the problem goes deeper.  The mock also fails when I tell it to return a real error.  This time it complains that the wrong type is returned.

So that you can reproduce all this, I've created a simple test case. See below.

My test program contains two tests TestSuccess and TestFailure.  TestSuccess reproduces the first problem, returning nil.  TestFailure reproduces the second problem, returning a real error.  If TestSuccess runs, it breaks and testing stops, so TestFailure never runs.  If you comment out TestSuccess, you can see what happens when TestFailure runs.

This is TestSuccess running:

$ go test
--- FAIL: TestSuccess (0.00s)
panic: interface conversion: interface is nil, not error [recovered]
    panic: interface conversion: interface is nil, not error

goroutine 5 [running]:
panic(0x638ce0, 0xc420014940)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc420094180)
    /usr/local/go/src/testing/testing.go:579 +0x25d
panic(0x638ce0, 0xc420014940)
    /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/goblimey/films/bug.(_MockTemplate).Execute(0xc420034038, 0x77c9c0, 0xc420034030, 0x617500, 0xc42000d208, 0xc42000d230, 0x1)
    /home/simon/eclipse.workspaces/films4/films/src/github.com/goblimey/films/bug/mock_template.go:26 +0x1e5
github.com/goblimey/films/bug.Fun(0x77ca00, 0xc420034038, 0x780300, 0xc420034030, 0xc42000d208, 0x0, 0x0)
    /home/simon/eclipse.workspaces/films4/films/src/github.com/goblimey/films/bug/bug_test.go:23 +0x8d
github.com/goblimey/films/bug.TestSuccess(0xc420094180)
    /home/simon/eclipse.workspaces/films4/films/src/github.com/goblimey/films/bug/bug_test.go:42 +0x217
testing.tRunner(0xc420094180, 0x69d3a8)
    /usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(_T).Run
    /usr/local/go/src/testing/testing.go:646 +0x2ec
exit status 2
FAIL    github.com/goblimey/films/bug   0.005s

With TestSuccess commented out, TestFailure runs and breaks:

$ go test
--- FAIL: TestFailure (0.00s)
panic: Return type doesn't match [recovered]
    panic: Return type doesn't match

goroutine 5 [running]:
panic(0x623ee0, 0xc42000d250)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc420094180)
    /usr/local/go/src/testing/testing.go:579 +0x25d
panic(0x623ee0, 0xc42000d250)
    /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/petergtz/pegomock/internal/verify.Argument(0x0, 0x68271f, 0x19, 0x0, 0x0, 0x0)
    /home/simon/gocode/src/github.com/petergtz/pegomock/internal/verify/verify.go:13 +0xbc
github.com/petergtz/pegomock.checkEquivalenceOf(0xc42000d240, 0x1, 0x1, 0xc42000d230, 0x1, 0x1)
    /home/simon/gocode/src/github.com/petergtz/pegomock/dsl.go:328 +0x13d
github.com/petergtz/pegomock.(_ongoingStubbing).ThenReturn(0xc420016730, 0xc42000d240, 0x1, 0x1, 0xc42000d208)
    /home/simon/gocode/src/github.com/petergtz/pegomock/dsl.go:318 +0x63
github.com/goblimey/films/bug.TestFailure(0xc420094180)
    /home/simon/eclipse.workspaces/films4/films/src/github.com/goblimey/films/bug/bug_test.go:65 +0x250
testing.tRunner(0xc420094180, 0x69d360)
    /usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(_T).Run
    /usr/local/go/src/testing/testing.go:646 +0x2ec
exit status 2
FAIL    github.com/goblimey/films/bug   0.005s

To run these tests, create a package called bug.  In there create template.go:

package bug

import (
    "io"
)

// The Template interface mimics some of the the html/Template functionality,
// allowing templates to be mocked.
type Template interface {
    // Execute executes the template
    Execute(wr io.Writer, data interface{}) error
}

Create two mocks:

$ pegomock generate --package bug --output=mock_template.go template.go
$ pegomock generate --package bug --output=mock_response_writer.go net/http ResponseWriter

Create this test program:

package bug

import (
    "errors"
    "net/http"
    "testing"

```
"github.com/petergtz/pegomock"
```

)

/*
To prepare:
pegomock generate --package bug --output=mock_template.go template.go
pegomock generate --package bug --output=mock_response_writer.go net/http ResponseWriter
*/
type Something struct {
    Contents int
}

// fun is the function to be tested.
func Fun(page Template, writer http.ResponseWriter, something *Something) error {
    return page.Execute(writer, something)
}

// Drive Fun() so that it does not return an error

func TestSuccess(t *testing.T) {

```
pegomock.RegisterMockTestingT(t)

var something Something
something.Contents = 1

mockWriter := NewMockResponseWriter()
mockTemplate := NewMockTemplate()

pegomock.When(mockTemplate.Execute(mockWriter, &something)).ThenReturn(nil)

err := Fun(mockTemplate, mockWriter, &something)

if err != nil {
    t.Errorf("TestSuccess %s", err.Error())
}
```

}

// Drive Fun() so that it returns an error
func TestFailure(t *testing.T) {

```
pegomock.RegisterMockTestingT(t)

var something Something
something.Contents = 1

mockWriter := NewMockResponseWriter()
mockTemplate := NewMockTemplate()

expectedError := errors.New("an error message")

pegomock.When(mockTemplate.Execute(mockWriter, &something)).ThenReturn(expectedError)

err := Fun(mockTemplate, mockWriter, &something)

if err == nil {
    t.Errorf("TestFailure - expected an error, got nil")
}
```

}

**Comment by petergtz** [comment]
Hi @goblimey,

I've just pushed a fix. Can you please try again? Please make sure that `$GOPATH/bin/pegomock` is really rebuilt with the newest version after you did a `go get -u github.com/petergtz/pegomock/pegomock` (don't miss the second pegomock in the path). Your generated files should definitely look different now.

Let me know if this fixes your use case. Thanks!

**Comment by petergtz** [comment]
@goblimey Please notice that as part of fixing the issue you reported here, I made a small API change: there is no `matcher` package anymore. Everything is in `github.com/petergtz/pegomock` now.

**Comment by goblimey** [comment]
Yes, that's all working now.  You can close this issue.

Thanks for the comment about
    go get -u github.com/petergtz/pegomock/pegomock 
rather than just
    go get -u github.com/petergtz/pegomock 
I probably would have got that wrong!

**Comment by petergtz** [comment]
Glad it works now. And thanks again for reporting it!
